name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r insta_trend_suggester/requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 insta_trend_suggester/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 insta_trend_suggester/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test import modules
      run: |
        cd insta_trend_suggester
        python -c "import models, db, gemini_utils, instagram_scraper, scheduler"
    
    - name: Test with pytest (if tests exist)
      run: |
        if [ -d "tests" ]; then
          pytest tests/
        else
          echo "No tests directory found, skipping tests"
        fi

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        cd insta_trend_suggester
        docker build -t instagram-trend-suggester .
    
    - name: Test Docker image
      run: |
        docker run --rm instagram-trend-suggester python -c "print('Docker build successful!')"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run security scan
      uses: pypa/gh-action-pip-audit@v1.1.0
      with:
        inputs: insta_trend_suggester/requirements.txt
        ignore-vulns: |
          GHSA-jfhm-5ghh-2f97
